require("nvchad.configs.lspconfig").defaults()

local servers = { "pyright", "intelephense", "laravel_ls", "ts_ls", "tailwindcss", "vue_ls", "html", "cssls", "twiggy_language_server", "emmet_ls"}
vim.lsp.enable(servers)


-- local lspconfig = require("lspconfig")
-- local lspconfig_util = lspconfig.util
--
-- -- NvChad's helpers
-- local on_attach = require("nvchad.configs.lspconfig").on_attach
-- local capabilities = require("nvchad.configs.lspconfig").capabilities
--
--
-- -- PHP (Intelephense)
-- lspconfig.intelephense.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "php", "blade" },
--   root_dir = lspconfig_util.root_pattern("composer.json", ".git"),
-- }
--
-- -- JavaScript/TypeScript (using the new name ts_ls)
-- lspconfig.ts_ls.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
--   root_dir = lspconfig_util.root_pattern("package.json"),
-- }
--
-- lspconfig.html.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
-- }
--
-- lspconfig.cssls.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
-- }
--
-- -- Tailwind CSS
-- lspconfig.tailwindcss.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "html", "css", "scss", "vue", "blade", "javascript", "typescript" },
--   root_dir = lspconfig_util.root_pattern("tailwind.config.js"),
-- }
--
-- -- Vue.js (Volar)
-- lspconfig.volar.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
--   filetypes = { "vue" },
--   init_options = {
--     typescript = {
--       tsdk = "node_modules/typescript/lib",
--     }
--   }
-- }
--
-- -- Python (Pyright)
-- lspconfig.pyright.setup {
--   on_attach = on_attach,
--   capabilities = capabilities,
--   root_dir = lspconfig_util.root_pattern("pyproject.toml", "setup.py", ".git"),
--   settings = {
--     python = {
--       analysis = {
--         autoSearchPaths = true,
--         useLibraryCodeForTypes = true,
--       },
--     },
--   },
-- }
